version: "3.9"
services:
  dealer:
    build: .
    ports:
      - 8626:8626
    environment:
      - DATABASE_DSN=user:pass@tcp(database:3306)/deal?charset=utf8&parseTime=True&loc=Local
      - MESSAGEQUEUE_URL=amqp://user:pass@mq:5672/
      - MESSAGEQUEUE_QUEUENAME=order
      - GIN_MODE=release
    depends_on:
      database:
        condition: service_healthy
      mq:
        condition: service_healthy

  database:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: deal
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10


  mq:
    image: rabbitmq
    restart: always
    ports:
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3