httpServer:
  domain: localhost
  port: 8626

database:
  dsn: "user:pass@tcp(localhost:3306)/deal?charset=utf8&parseTime=True&loc=Local"

messageQueue:
  url: "amqp://user:pass@localhost:5672/"
  queueName: order

redis:
  address: "localhost:6379"
  dialTimeout: 10s
  expiration: 6h

logger:
  level: -1